baseURL = "https://evilnick.github.io/k8screw-hugo/"
languageCode = "en-us"
title = "K8s Team blog"
theme = "ananke"


# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/evilnick"

#[[params.social]]
#name = "Email"
#icon = "fas fa-envelope"
#cmd = "mailto:example@example.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"

